version: "3.8"

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=postgress
      - POSTGRES_PASSWORD=123
    networks:
      - network-app
    restart: always
    ports:
      - "5432:5432"

  app:
    depends_on:
      - postgres_db
    container_name: my-app
    build: ./menu_api/
    restart: always
    networks:
      - network-app
    ports:
      - "5011:5011"
    healthcheck:
      test: curl --fail http://0.0.0.0:5432 || exit 1
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3

networks:
    network-app:
      driver: bridge

